
const users = [
  { username: "hospital1", password: "admin", role: "hospital" },
  { username: "hospital2", password: "admin2", role: "hospital" },
  { username: "hospital3", password: "admin3", role: "hospital" },
  {
    username: "john",
    password: "1234",
    role: "person",
    name: "John Doe",
    age: 28,
    bloodGroup: "A+",
    emergencyContact: "9876543210",
    allergies: ["Penicillin", "Peanuts"],
    medications: ["Aspirin", "Metformin", "Lisinopril"],
    conditions: ["Asthma", "Type 2 Diabetes"],
    surgeries: ["Appendectomy - 2019"],
    lastVisit: "2025-07-15",
    vaccinations: ["COVID-19", "Tetanus", "Hepatitis B"],
    notes: "Patient experiences seasonal asthma attacks. Requires inhaler during weather changes."
  },
  {
    username: "alice",
    password: "abcd",
    role: "person",
    name: "Alice Smith",
    age: 34,
    bloodGroup: "O-",
    emergencyContact: "9123456780",
    allergies: ["Latex"],
    medications: ["Ibuprofen", "Levothyroxine"],
    conditions: ["Hypothyroidism"],
    surgeries: [],
    lastVisit: "2025-06-30",
    vaccinations: ["MMR", "HPV"],
    notes: "Regular thyroid checkups needed. No known hereditary conditions."
  },
  {
    username: "mike",
    password: "mike123",
    role: "person",
    name: "Mike Johnson",
    age: 45,
    bloodGroup: "B+",
    emergencyContact: "9988776655",
    allergies: ["Shellfish", "Dust"],
    medications: ["Albuterol", "Omeprazole"],
    conditions: ["COPD", "Acid Reflux"],
    surgeries: ["Gallbladder Removal - 2020"],
    lastVisit: "2025-05-12",
    vaccinations: ["Influenza", "COVID-19 Booster"],
    notes: "Uses inhaler twice a day. Needs respiratory checkups every 6 months."
  },
  {
    username: "nina",
    password: "nina321",
    role: "person",
    name: "Nina Patel",
    age: 29,
    bloodGroup: "AB+",
    emergencyContact: "9001122334",
    allergies: ["None"],
    medications: ["None"],
    conditions: ["Anemia"],
    surgeries: ["C-section - 2023"],
    lastVisit: "2025-07-20",
    vaccinations: ["DPT", "Hepatitis A"],
    notes: "Iron supplements prescribed. Postnatal care ongoing."
  }
];
